// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    user_id, email_id, password_hash
) VALUES (
    $1, $2, $3
) RETURNING user_id, email_id, password_hash, created_at, updated_at
`

type CreateCredentialParams struct {
	UserID       uuid.UUID
	EmailID      string
	PasswordHash string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential, arg.UserID, arg.EmailID, arg.PasswordHash)
	var i Credential
	err := row.Scan(
		&i.UserID,
		&i.EmailID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByEmail = `-- name: GetCredentialByEmail :one
SELECT c.user_id, c.email_id, c.password_hash, u.full_name, u.role, u.tenant_id FROM credentials c JOIN users u ON c.user_id = u.id WHERE c.email_id = $1
`

type GetCredentialByEmailRow struct {
	UserID       uuid.UUID
	EmailID      string
	PasswordHash string
	FullName     string
	Role         string
	TenantID     uuid.UUID
}

func (q *Queries) GetCredentialByEmail(ctx context.Context, emailID string) (GetCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByEmail, emailID)
	var i GetCredentialByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.EmailID,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.TenantID,
	)
	return i, err
}

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT c.user_id, c.email_id, c.password_hash, u.full_name, u.role, u.tenant_id FROM credentials c JOIN users u ON c.user_id = u.id WHERE c.user_id = $1
`

type GetCredentialByUserIDRow struct {
	UserID       uuid.UUID
	EmailID      string
	PasswordHash string
	FullName     string
	Role         string
	TenantID     uuid.UUID
}

func (q *Queries) GetCredentialByUserID(ctx context.Context, userID uuid.UUID) (GetCredentialByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, userID)
	var i GetCredentialByUserIDRow
	err := row.Scan(
		&i.UserID,
		&i.EmailID,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.TenantID,
	)
	return i, err
}
