// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: farm.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createFarm = `-- name: CreateFarm :one
INSERT INTO farms (name, location, latitude, longitude, total_area, area_unit, notes, tenant_id, farm_type_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, farm_type_id, name, location, latitude, longitude, total_area, area_unit, notes, is_active, created_at, updated_at
`

type CreateFarmParams struct {
	Name       string
	Location   *string
	Latitude   *float64
	Longitude  *float64
	TotalArea  *float64
	AreaUnit   string
	Notes      *string
	TenantID   uuid.UUID
	FarmTypeID uuid.UUID
}

func (q *Queries) CreateFarm(ctx context.Context, arg CreateFarmParams) (Farm, error) {
	row := q.db.QueryRow(ctx, createFarm,
		arg.Name,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
		arg.TotalArea,
		arg.AreaUnit,
		arg.Notes,
		arg.TenantID,
		arg.FarmTypeID,
	)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FarmTypeID,
		&i.Name,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.TotalArea,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFarms = `-- name: ListFarms :many
SELECT id, tenant_id, farm_type_id, name, location, latitude, longitude, total_area, area_unit, notes, is_active, created_at, updated_at FROM farms
WHERE tenant_id = $1
AND is_active = $2
ORDER BY created_at DESC
`

type ListFarmsParams struct {
	TenantID uuid.UUID
	IsActive bool
}

func (q *Queries) ListFarms(ctx context.Context, arg ListFarmsParams) ([]Farm, error) {
	rows, err := q.db.Query(ctx, listFarms, arg.TenantID, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Farm
	for rows.Next() {
		var i Farm
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FarmTypeID,
			&i.Name,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.TotalArea,
			&i.AreaUnit,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleFarmIsActive = `-- name: ToggleFarmIsActive :one
UPDATE farms
SET is_active = $2
WHERE id = $1
RETURNING id, tenant_id, farm_type_id, name, location, latitude, longitude, total_area, area_unit, notes, is_active, created_at, updated_at
`

type ToggleFarmIsActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) ToggleFarmIsActive(ctx context.Context, arg ToggleFarmIsActiveParams) (Farm, error) {
	row := q.db.QueryRow(ctx, toggleFarmIsActive, arg.ID, arg.IsActive)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FarmTypeID,
		&i.Name,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.TotalArea,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFarm = `-- name: UpdateFarm :one
UPDATE farms
SET name = $2, location = $3, latitude = $4, longitude = $5, total_area = $6, area_unit = $7, notes = $8, updated_at = now()
WHERE id = $1
RETURNING id, tenant_id, farm_type_id, name, location, latitude, longitude, total_area, area_unit, notes, is_active, created_at, updated_at
`

type UpdateFarmParams struct {
	ID        uuid.UUID
	Name      string
	Location  *string
	Latitude  *float64
	Longitude *float64
	TotalArea *float64
	AreaUnit  string
	Notes     *string
}

func (q *Queries) UpdateFarm(ctx context.Context, arg UpdateFarmParams) (Farm, error) {
	row := q.db.QueryRow(ctx, updateFarm,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
		arg.TotalArea,
		arg.AreaUnit,
		arg.Notes,
	)
	var i Farm
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FarmTypeID,
		&i.Name,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.TotalArea,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
