// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lookup.sql

package queries

import (
	"context"
)

const listFarmTypes = `-- name: ListFarmTypes :many
SELECT id, name, display_name, description FROM farm_types ORDER BY name
`

func (q *Queries) ListFarmTypes(ctx context.Context) ([]FarmType, error) {
	rows, err := q.db.Query(ctx, listFarmTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FarmType
	for rows.Next() {
		var i FarmType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
