// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	UserID       uuid.UUID
	EmailID      string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Farm struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	FarmTypeID uuid.UUID
	Name       string
	Location   *string
	Latitude   pgtype.Numeric
	Longitude  pgtype.Numeric
	TotalArea  pgtype.Numeric
	AreaUnit   string
	Notes      *string
	IsActive   bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type FarmType struct {
	ID          uuid.UUID
	Name        string
	DisplayName string
	Description *string
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt *time.Time
	UserAgent *string
	Ip        *string
	CreatedAt time.Time
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	Subdomain   string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	EmailID        string
	FullName       string
	ProfilePicture *string
	Role           string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastActiveAt   *time.Time
	DeletedAt      *time.Time
}

type UserInvitation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TenantID   uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
}
