// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type Credential struct {
	UserID       uuid.UUID
	EmailID      string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Farm struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	FarmTypeID uuid.UUID
	Name       string
	Location   *string
	Latitude   *float64
	Longitude  *float64
	TotalArea  *float64
	AreaUnit   string
	Notes      *string
	IsActive   bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type FarmType struct {
	ID          uuid.UUID
	Name        string
	DisplayName string
	Description *string
}

type HydroSystemType struct {
	ID          uuid.UUID
	Name        string
	DisplayName string
	Description *string
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt *time.Time
	UserAgent *string
	Ip        *string
	CreatedAt time.Time
}

type SoilType struct {
	ID             uuid.UUID
	Name           string
	DisplayName    string
	WaterRetention string
	Drainage       string
	Description    *string
}

type Tenant struct {
	ID          uuid.UUID
	Name        string
	Subdomain   string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	EmailID        string
	FullName       string
	ProfilePicture *string
	Role           string
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	LastActiveAt   *time.Time
	DeletedAt      *time.Time
}

type UserInvitation struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TenantID   uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
}

type Zone struct {
	ID         uuid.UUID
	FarmID     uuid.UUID
	TenantID   uuid.UUID
	ZoneTypeID uuid.UUID
	Name       string
	Area       *float64
	AreaUnit   string
	Notes      *string
	IsActive   bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ZoneHydroDetail struct {
	ZoneID                uuid.UUID
	HydroSystemTypeID     uuid.UUID
	GrowMedium            *string
	ReservoirVolumeLiters *float64
	NumberOfSlots         *int32
}

type ZoneSoilDetail struct {
	ZoneID     uuid.UUID
	SoilTypeID uuid.UUID
}

type ZoneType struct {
	ID              uuid.UUID
	Name            string
	DisplayName     string
	CultivationMode string
	Description     *string
}
