// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (user_id, otp_hash, expires_at)
VALUES ($1, $2, $3) RETURNING id, user_id, otp_hash, reset_token, attempts, max_attempts, is_used, expires_at, created_at, updated_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID
	OtpHash   string
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.OtpHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.ResetToken,
		&i.Attempts,
		&i.MaxAttempts,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
