// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckTenantExistsBySubdomain(ctx context.Context, subdomain string) (bool, error)
	CheckUserExistsByEmailID(ctx context.Context, emailID string) (bool, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmailID(ctx context.Context, emailID string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
