// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const checkTenantExistsBySubdomain = `-- name: CheckTenantExistsBySubdomain :one
SELECT EXISTS (SELECT 1 FROM tenants WHERE subdomain = $1)
`

func (q *Queries) CheckTenantExistsBySubdomain(ctx context.Context, subdomain string) (bool, error) {
	row := q.db.QueryRow(ctx, checkTenantExistsBySubdomain, subdomain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, subdomain) VALUES ($1, $2) RETURNING id, name, subdomain, description, created_at, updated_at
`

type CreateTenantParams struct {
	Name      string
	Subdomain string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Subdomain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants SET name = $2, description = $3, updated_at = now() WHERE id = $1 RETURNING id, name, subdomain, description, created_at, updated_at
`

type UpdateTenantParams struct {
	ID          uuid.UUID
	Name        string
	Description *string
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.ID, arg.Name, arg.Description)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Subdomain,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
