// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const checkUserExistsByEmailID = `-- name: CheckUserExistsByEmailID :one
SELECT EXISTS (SELECT 1 FROM users WHERE email_id = $1)
`

func (q *Queries) CheckUserExistsByEmailID(ctx context.Context, emailID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExistsByEmailID, emailID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name, email_id, password_hash, role, status, tenant_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, email_id, password_hash, full_name, role, status, created_at, updated_at
`

type CreateUserParams struct {
	FullName     string
	EmailID      string
	PasswordHash string
	Role         string
	Status       string
	TenantID     uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.EmailID,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
