// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_invitation.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserInvitation = `-- name: CreateUserInvitation :one
INSERT INTO user_invitations (
    user_id, tenant_id, token_hash, expires_at, created_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, tenant_id, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at
`

type CreateUserInvitationParams struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedBy uuid.UUID
}

func (q *Queries) CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, createUserInvitation,
		arg.UserID,
		arg.TenantID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserInvitationByID = `-- name: GetUserInvitationByID :one
SELECT id, user_id, tenant_id, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at FROM user_invitations WHERE id = $1
`

func (q *Queries) GetUserInvitationByID(ctx context.Context, id uuid.UUID) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getUserInvitationByID, id)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getUserInvitationByTokenHash = `-- name: GetUserInvitationByTokenHash :one
SELECT id, user_id, tenant_id, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at FROM user_invitations WHERE token_hash = $1
`

func (q *Queries) GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getUserInvitationByTokenHash, tokenHash)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const markUserInvitationAccepted = `-- name: MarkUserInvitationAccepted :one
UPDATE user_invitations
SET accepted_at = now()
WHERE id = $1
RETURNING id, user_id, tenant_id, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at
`

func (q *Queries) MarkUserInvitationAccepted(ctx context.Context, id uuid.UUID) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, markUserInvitationAccepted, id)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOpenUserInvitationsByUserID = `-- name: RevokeOpenUserInvitationsByUserID :exec
UPDATE user_invitations
SET revoked_at = now()
WHERE user_id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeOpenUserInvitationsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeOpenUserInvitationsByUserID, userID)
	return err
}

const revokeUserInvitationByID = `-- name: RevokeUserInvitationByID :exec
UPDATE user_invitations SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeUserInvitationByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserInvitationByID, id)
	return err
}
