// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkUserExistsByEmailID = `-- name: CheckUserExistsByEmailID :one
SELECT EXISTS (SELECT 1 FROM users WHERE email_id = $1)
`

func (q *Queries) CheckUserExistsByEmailID(ctx context.Context, emailID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExistsByEmailID, emailID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name, email_id, password_hash, role, status, tenant_id
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, email_id, password_hash, full_name, profile_picture, role, status, created_at, updated_at
`

type CreateUserParams struct {
	FullName     string
	EmailID      string
	PasswordHash string
	Role         string
	Status       string
	TenantID     uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.EmailID,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.PasswordHash,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailID = `-- name: GetUserByEmailID :one
SELECT id, tenant_id, email_id, password_hash, full_name, profile_picture, role, status, created_at, updated_at FROM users WHERE email_id = $1
`

func (q *Queries) GetUserByEmailID(ctx context.Context, emailID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailID, emailID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.PasswordHash,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email_id, password_hash, full_name, profile_picture, role, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.PasswordHash,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfileDetails = `-- name: GetUserProfileDetails :one
SELECT u.id, u.full_name, u.email_id, u.role, u.profile_picture, u.status, u.created_at, t.id as tenant_id, t.name as tenant_name, t.subdomain, t.description, t.created_at as tenant_created_at FROM users u JOIN tenants t ON u.tenant_id = t.id WHERE u.id = $1
`

type GetUserProfileDetailsRow struct {
	ID              uuid.UUID
	FullName        string
	EmailID         string
	Role            string
	ProfilePicture  *string
	Status          string
	CreatedAt       time.Time
	TenantID        uuid.UUID
	TenantName      string
	Subdomain       string
	Description     *string
	TenantCreatedAt time.Time
}

func (q *Queries) GetUserProfileDetails(ctx context.Context, id uuid.UUID) (GetUserProfileDetailsRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileDetails, id)
	var i GetUserProfileDetailsRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.EmailID,
		&i.Role,
		&i.ProfilePicture,
		&i.Status,
		&i.CreatedAt,
		&i.TenantID,
		&i.TenantName,
		&i.Subdomain,
		&i.Description,
		&i.TenantCreatedAt,
	)
	return i, err
}
