// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const checkUserExistsByEmailID = `-- name: CheckUserExistsByEmailID :one
SELECT EXISTS (SELECT 1 FROM users WHERE email_id = $1)
`

func (q *Queries) CheckUserExistsByEmailID(ctx context.Context, emailID string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExistsByEmailID, emailID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO users (
    full_name, email_id, role, status, tenant_id, profile_picture
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at
`

type CreateMemberParams struct {
	FullName       string
	EmailID        string
	Role           string
	Status         string
	TenantID       uuid.UUID
	ProfilePicture *string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (User, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.FullName,
		arg.EmailID,
		arg.Role,
		arg.Status,
		arg.TenantID,
		arg.ProfilePicture,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name, email_id, role, status, tenant_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at
`

type CreateUserParams struct {
	FullName string
	EmailID  string
	Role     string
	Status   string
	TenantID uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.EmailID,
		arg.Role,
		arg.Status,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
UPDATE users SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getUserByEmailID = `-- name: GetUserByEmailID :one
SELECT id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at FROM users WHERE email_id = $1
`

func (q *Queries) GetUserByEmailID(ctx context.Context, emailID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailID, emailID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserProfileDetails = `-- name: GetUserProfileDetails :one
SELECT u.id, u.full_name, u.email_id, u.role, u.profile_picture, u.status, u.created_at, u.last_active_at, t.id as tenant_id, t.name as tenant_name, t.subdomain, t.description, t.created_at as tenant_created_at FROM users u JOIN tenants t ON u.tenant_id = t.id WHERE u.id = $1
`

type GetUserProfileDetailsRow struct {
	ID              uuid.UUID
	FullName        string
	EmailID         string
	Role            string
	ProfilePicture  *string
	Status          string
	CreatedAt       time.Time
	LastActiveAt    *time.Time
	TenantID        uuid.UUID
	TenantName      string
	Subdomain       string
	Description     *string
	TenantCreatedAt time.Time
}

func (q *Queries) GetUserProfileDetails(ctx context.Context, id uuid.UUID) (GetUserProfileDetailsRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileDetails, id)
	var i GetUserProfileDetailsRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.EmailID,
		&i.Role,
		&i.ProfilePicture,
		&i.Status,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.TenantID,
		&i.TenantName,
		&i.Subdomain,
		&i.Description,
		&i.TenantCreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at FROM users
WHERE tenant_id = $1 AND id != $2 AND deleted_at IS NULL
ORDER BY last_active_at DESC NULLS LAST, full_name
`

type ListMembersParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.TenantID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EmailID,
			&i.FullName,
			&i.ProfilePicture,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserLastActive = `-- name: TouchUserLastActive :exec
UPDATE users SET last_active_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLastActive(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastActive, id)
	return err
}

const updateMember = `-- name: UpdateMember :one
UPDATE users SET full_name = $2, profile_picture = $3, role = $4, updated_at = now() WHERE id = $1 RETURNING id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at
`

type UpdateMemberParams struct {
	ID             uuid.UUID
	FullName       string
	ProfilePicture *string
	Role           string
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (User, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.FullName,
		arg.ProfilePicture,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET full_name = $2, profile_picture = $3, updated_at = now() WHERE id = $1 RETURNING id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID             uuid.UUID
	FullName       string
	ProfilePicture *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.ID, arg.FullName, arg.ProfilePicture)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2 WHERE id = $1 RETURNING id, tenant_id, email_id, full_name, profile_picture, role, status, created_at, updated_at, last_active_at, deleted_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EmailID,
		&i.FullName,
		&i.ProfilePicture,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.DeletedAt,
	)
	return i, err
}
