// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_invitation.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserInvitation = `-- name: CreateUserInvitation :one
INSERT INTO user_invitations (
    user_id, tenant_id, token_hash, expires_at, created_by
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, tenant_id, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at
`

type CreateUserInvitationParams struct {
	UserID    uuid.UUID
	TenantID  uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	CreatedBy uuid.UUID
}

func (q *Queries) CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, createUserInvitation,
		arg.UserID,
		arg.TenantID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationDetailsByTokenHash = `-- name: GetInvitationDetailsByTokenHash :one
SELECT i.id, i.user_id, i.tenant_id, i.token_hash, i.expires_at, i.accepted_at, i.revoked_at, i.created_by, i.created_at, u.full_name, u.email_id, u.role, t.name AS tenant_name
FROM user_invitations i
JOIN users u ON u.id = i.user_id
JOIN tenants t ON t.id = i.tenant_id
WHERE i.token_hash = $1
`

type GetInvitationDetailsByTokenHashRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TenantID   uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	RevokedAt  *time.Time
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	FullName   string
	EmailID    string
	Role       string
	TenantName string
}

func (q *Queries) GetInvitationDetailsByTokenHash(ctx context.Context, tokenHash string) (GetInvitationDetailsByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationDetailsByTokenHash, tokenHash)
	var i GetInvitationDetailsByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FullName,
		&i.EmailID,
		&i.Role,
		&i.TenantName,
	)
	return i, err
}

const getUserInvitationByTokenHash = `-- name: GetUserInvitationByTokenHash :one
SELECT id, user_id, tenant_id, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at FROM user_invitations WHERE token_hash = $1
`

func (q *Queries) GetUserInvitationByTokenHash(ctx context.Context, tokenHash string) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, getUserInvitationByTokenHash, tokenHash)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const markUserInvitationAccepted = `-- name: MarkUserInvitationAccepted :one
UPDATE user_invitations
SET accepted_at = now()
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
RETURNING id, user_id, tenant_id, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at
`

func (q *Queries) MarkUserInvitationAccepted(ctx context.Context, id uuid.UUID) (UserInvitation, error) {
	row := q.db.QueryRow(ctx, markUserInvitationAccepted, id)
	var i UserInvitation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
