// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zone.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createZone = `-- name: CreateZone :one
INSERT INTO zones (farm_id, tenant_id, zone_type_id, name, area, area_unit, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, farm_id, tenant_id, zone_type_id, name, area, area_unit, notes, is_active, created_at, updated_at
`

type CreateZoneParams struct {
	FarmID     uuid.UUID
	TenantID   uuid.UUID
	ZoneTypeID uuid.UUID
	Name       string
	Area       *float64
	AreaUnit   string
	Notes      *string
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.FarmID,
		arg.TenantID,
		arg.ZoneTypeID,
		arg.Name,
		arg.Area,
		arg.AreaUnit,
		arg.Notes,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TenantID,
		&i.ZoneTypeID,
		&i.Name,
		&i.Area,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZones = `-- name: ListZones :many
SELECT z.id, z.farm_id, z.tenant_id, z.zone_type_id, z.name, z.area, z.area_unit, z.notes, z.is_active, z.created_at, z.updated_at, zt.display_name AS zone_type_name, zt.cultivation_mode, zt.description FROM zones z
JOIN zone_types zt ON z.zone_type_id = zt.id
WHERE tenant_id = $1
AND is_active = $2
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListZonesParams struct {
	TenantID uuid.UUID
	IsActive bool
	Limit    int32
	Offset   int32
}

type ListZonesRow struct {
	ID              uuid.UUID
	FarmID          uuid.UUID
	TenantID        uuid.UUID
	ZoneTypeID      uuid.UUID
	Name            string
	Area            *float64
	AreaUnit        string
	Notes           *string
	IsActive        bool
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ZoneTypeName    string
	CultivationMode string
	Description     *string
}

func (q *Queries) ListZones(ctx context.Context, arg ListZonesParams) ([]ListZonesRow, error) {
	rows, err := q.db.Query(ctx, listZones,
		arg.TenantID,
		arg.IsActive,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListZonesRow
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.TenantID,
			&i.ZoneTypeID,
			&i.Name,
			&i.Area,
			&i.AreaUnit,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ZoneTypeName,
			&i.CultivationMode,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleZoneIsActive = `-- name: ToggleZoneIsActive :one
UPDATE zones
SET is_active = $2
WHERE id = $1
RETURNING id, farm_id, tenant_id, zone_type_id, name, area, area_unit, notes, is_active, created_at, updated_at
`

type ToggleZoneIsActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) ToggleZoneIsActive(ctx context.Context, arg ToggleZoneIsActiveParams) (Zone, error) {
	row := q.db.QueryRow(ctx, toggleZoneIsActive, arg.ID, arg.IsActive)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TenantID,
		&i.ZoneTypeID,
		&i.Name,
		&i.Area,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones
SET name = $2, area = $3, area_unit = $4, notes = $5, updated_at = now()
WHERE id = $1
RETURNING id, farm_id, tenant_id, zone_type_id, name, area, area_unit, notes, is_active, created_at, updated_at
`

type UpdateZoneParams struct {
	ID       uuid.UUID
	Name     string
	Area     *float64
	AreaUnit string
	Notes    *string
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.ID,
		arg.Name,
		arg.Area,
		arg.AreaUnit,
		arg.Notes,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TenantID,
		&i.ZoneTypeID,
		&i.Name,
		&i.Area,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
