// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zone_soil_details.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createZoneSoilDetails = `-- name: CreateZoneSoilDetails :one
INSERT INTO zone_soil_details (zone_id, soil_type_id)
VALUES ($1, $2)
RETURNING zone_id, soil_type_id
`

type CreateZoneSoilDetailsParams struct {
	ZoneID     uuid.UUID
	SoilTypeID uuid.UUID
}

func (q *Queries) CreateZoneSoilDetails(ctx context.Context, arg CreateZoneSoilDetailsParams) (ZoneSoilDetail, error) {
	row := q.db.QueryRow(ctx, createZoneSoilDetails, arg.ZoneID, arg.SoilTypeID)
	var i ZoneSoilDetail
	err := row.Scan(&i.ZoneID, &i.SoilTypeID)
	return i, err
}

const updateZoneSoilDetails = `-- name: UpdateZoneSoilDetails :one
UPDATE zone_soil_details
SET
    soil_type_id = $2
WHERE zone_id = $1
RETURNING zone_id, soil_type_id
`

type UpdateZoneSoilDetailsParams struct {
	ZoneID     uuid.UUID
	SoilTypeID uuid.UUID
}

func (q *Queries) UpdateZoneSoilDetails(ctx context.Context, arg UpdateZoneSoilDetailsParams) (ZoneSoilDetail, error) {
	row := q.db.QueryRow(ctx, updateZoneSoilDetails, arg.ZoneID, arg.SoilTypeID)
	var i ZoneSoilDetail
	err := row.Scan(&i.ZoneID, &i.SoilTypeID)
	return i, err
}
