// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zone.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countZonesByStatus = `-- name: CountZonesByStatus :one
SELECT count(*) FILTER (WHERE is_active)                              AS active,
       count(*) FILTER (WHERE NOT is_active)                          AS inactive,
       count(*)                                                       AS total,
       count(*) FILTER (WHERE zone_type_id = $2::uuid)                AS by_type  -- or GROUP BY for all chips
FROM zones WHERE tenant_id = $1 AND ($3::uuid IS NULL OR farm_id = $3)
`

type CountZonesByStatusParams struct {
	TenantID   uuid.UUID
	ZoneTypeID *uuid.UUID
	FarmID     *uuid.UUID
}

type CountZonesByStatusRow struct {
	Active   int64
	Inactive int64
	Total    int64
	ByType   int64
}

func (q *Queries) CountZonesByStatus(ctx context.Context, arg CountZonesByStatusParams) (CountZonesByStatusRow, error) {
	row := q.db.QueryRow(ctx, countZonesByStatus, arg.TenantID, arg.ZoneTypeID, arg.FarmID)
	var i CountZonesByStatusRow
	err := row.Scan(
		&i.Active,
		&i.Inactive,
		&i.Total,
		&i.ByType,
	)
	return i, err
}

const createZone = `-- name: CreateZone :one
INSERT INTO zones (farm_id, tenant_id, zone_type_id, name, area, area_unit, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (farm_id, name) WHERE is_active DO NOTHING
RETURNING id, farm_id, tenant_id, zone_type_id, name, area, area_unit, notes, is_active, created_at, updated_at
`

type CreateZoneParams struct {
	FarmID     uuid.UUID
	TenantID   uuid.UUID
	ZoneTypeID uuid.UUID
	Name       string
	Area       *float64
	AreaUnit   string
	Notes      *string
}

func (q *Queries) CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, createZone,
		arg.FarmID,
		arg.TenantID,
		arg.ZoneTypeID,
		arg.Name,
		arg.Area,
		arg.AreaUnit,
		arg.Notes,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TenantID,
		&i.ZoneTypeID,
		&i.Name,
		&i.Area,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listZones = `-- name: ListZones :many
SELECT z.id, z.farm_id, z.tenant_id, z.zone_type_id, z.name, z.area, z.area_unit, z.notes, z.is_active, z.created_at, z.updated_at, zt.name AS zone_type_name, zt.cultivation_mode, zt.display_name AS zone_type_display_name,
f.name AS farm_name,
zsd.soil_type_id, st.display_name AS soil_type_display_name,
st.water_retention AS soil_water_retention, st.drainage AS soil_drainage,
zhd.hydro_system_type_id, hst.display_name AS hydro_system_type_display_name,
zhd.grow_medium, zhd.reservoir_volume_liters, zhd.number_of_slots
FROM zones z
JOIN zone_types zt ON z.zone_type_id = zt.id
JOIN farms f ON z.farm_id = f.id
LEFT JOIN zone_soil_details zsd ON zsd.zone_id = z.id
LEFT JOIN soil_types st ON st.id = zsd.soil_type_id
LEFT JOIN zone_hydro_details zhd ON zhd.zone_id = z.id
LEFT JOIN hydro_system_types hst ON hst.id = zhd.hydro_system_type_id
WHERE z.tenant_id = $1
  AND ($4::uuid IS NULL OR z.farm_id = $4)
  AND ($5::uuid IS NULL OR z.zone_type_id = $5)
  AND ($6::bool IS NULL OR z.is_active = $6)
  AND ($7::text IS NULL
       OR z.name ILIKE '%' || $7 || '%'
       OR f.name ILIKE '%' || $7 || '%')
ORDER BY z.updated_at DESC
LIMIT $2
OFFSET $3
`

type ListZonesParams struct {
	TenantID   uuid.UUID
	Limit      int32
	Offset     int32
	FarmID     *uuid.UUID
	ZoneTypeID *uuid.UUID
	IsActive   *bool
	Search     *string
}

type ListZonesRow struct {
	ID                         uuid.UUID
	FarmID                     uuid.UUID
	TenantID                   uuid.UUID
	ZoneTypeID                 uuid.UUID
	Name                       string
	Area                       *float64
	AreaUnit                   string
	Notes                      *string
	IsActive                   bool
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	ZoneTypeName               string
	CultivationMode            string
	ZoneTypeDisplayName        string
	FarmName                   string
	SoilTypeID                 *uuid.UUID
	SoilTypeDisplayName        *string
	SoilWaterRetention         *string
	SoilDrainage               *string
	HydroSystemTypeID          *uuid.UUID
	HydroSystemTypeDisplayName *string
	GrowMedium                 *string
	ReservoirVolumeLiters      *float64
	NumberOfSlots              *int32
}

func (q *Queries) ListZones(ctx context.Context, arg ListZonesParams) ([]ListZonesRow, error) {
	rows, err := q.db.Query(ctx, listZones,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.FarmID,
		arg.ZoneTypeID,
		arg.IsActive,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListZonesRow
	for rows.Next() {
		var i ListZonesRow
		if err := rows.Scan(
			&i.ID,
			&i.FarmID,
			&i.TenantID,
			&i.ZoneTypeID,
			&i.Name,
			&i.Area,
			&i.AreaUnit,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ZoneTypeName,
			&i.CultivationMode,
			&i.ZoneTypeDisplayName,
			&i.FarmName,
			&i.SoilTypeID,
			&i.SoilTypeDisplayName,
			&i.SoilWaterRetention,
			&i.SoilDrainage,
			&i.HydroSystemTypeID,
			&i.HydroSystemTypeDisplayName,
			&i.GrowMedium,
			&i.ReservoirVolumeLiters,
			&i.NumberOfSlots,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleZoneIsActive = `-- name: ToggleZoneIsActive :one
UPDATE zones
SET is_active = $2
WHERE id = $1
RETURNING id, farm_id, tenant_id, zone_type_id, name, area, area_unit, notes, is_active, created_at, updated_at
`

type ToggleZoneIsActiveParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) ToggleZoneIsActive(ctx context.Context, arg ToggleZoneIsActiveParams) (Zone, error) {
	row := q.db.QueryRow(ctx, toggleZoneIsActive, arg.ID, arg.IsActive)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TenantID,
		&i.ZoneTypeID,
		&i.Name,
		&i.Area,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateZone = `-- name: UpdateZone :one
UPDATE zones
SET name = $2, area = $3, area_unit = $4, notes = $5, updated_at = now()
WHERE id = $1
RETURNING id, farm_id, tenant_id, zone_type_id, name, area, area_unit, notes, is_active, created_at, updated_at
`

type UpdateZoneParams struct {
	ID       uuid.UUID
	Name     string
	Area     *float64
	AreaUnit string
	Notes    *string
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error) {
	row := q.db.QueryRow(ctx, updateZone,
		arg.ID,
		arg.Name,
		arg.Area,
		arg.AreaUnit,
		arg.Notes,
	)
	var i Zone
	err := row.Scan(
		&i.ID,
		&i.FarmID,
		&i.TenantID,
		&i.ZoneTypeID,
		&i.Name,
		&i.Area,
		&i.AreaUnit,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
