// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zone_hydro_details.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createZoneHydroDetails = `-- name: CreateZoneHydroDetails :one
INSERT INTO zone_hydro_details (
    zone_id,
    hydro_system_type_id,
    grow_medium,
    reservoir_volume_liters,
    number_of_slots
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING zone_id, hydro_system_type_id, grow_medium, reservoir_volume_liters, number_of_slots
`

type CreateZoneHydroDetailsParams struct {
	ZoneID                uuid.UUID
	HydroSystemTypeID     uuid.UUID
	GrowMedium            *string
	ReservoirVolumeLiters *float64
	NumberOfSlots         *int32
}

func (q *Queries) CreateZoneHydroDetails(ctx context.Context, arg CreateZoneHydroDetailsParams) (ZoneHydroDetail, error) {
	row := q.db.QueryRow(ctx, createZoneHydroDetails,
		arg.ZoneID,
		arg.HydroSystemTypeID,
		arg.GrowMedium,
		arg.ReservoirVolumeLiters,
		arg.NumberOfSlots,
	)
	var i ZoneHydroDetail
	err := row.Scan(
		&i.ZoneID,
		&i.HydroSystemTypeID,
		&i.GrowMedium,
		&i.ReservoirVolumeLiters,
		&i.NumberOfSlots,
	)
	return i, err
}

const updateZoneHydroDetails = `-- name: UpdateZoneHydroDetails :one
UPDATE zone_hydro_details
SET
    hydro_system_type_id = $2,
    grow_medium = $3,
    reservoir_volume_liters = $4,
    number_of_slots = $5
WHERE zone_id = $1
RETURNING zone_id, hydro_system_type_id, grow_medium, reservoir_volume_liters, number_of_slots
`

type UpdateZoneHydroDetailsParams struct {
	ZoneID                uuid.UUID
	HydroSystemTypeID     uuid.UUID
	GrowMedium            *string
	ReservoirVolumeLiters *float64
	NumberOfSlots         *int32
}

func (q *Queries) UpdateZoneHydroDetails(ctx context.Context, arg UpdateZoneHydroDetailsParams) (ZoneHydroDetail, error) {
	row := q.db.QueryRow(ctx, updateZoneHydroDetails,
		arg.ZoneID,
		arg.HydroSystemTypeID,
		arg.GrowMedium,
		arg.ReservoirVolumeLiters,
		arg.NumberOfSlots,
	)
	var i ZoneHydroDetail
	err := row.Scan(
		&i.ZoneID,
		&i.HydroSystemTypeID,
		&i.GrowMedium,
		&i.ReservoirVolumeLiters,
		&i.NumberOfSlots,
	)
	return i, err
}
