/**
 * Seed farms — a curated set of realistic-looking farms so the list page
 * feels alive on first load. Stored in localStorage only the first time the
 * user opens the Farms page; subsequent edits are theirs.
 *
 * Each farm uses one of the five FarmTypeArt variants so the hero art
 * stays varied across the grid.
 */
export const SEED_FARMS = [
  {
    id: "farm-001",
    name: "Sunrise Acres",
    farmType: "outdoor",
    location: "Pune, Maharashtra",
    sizeAcres: 12.5,
    soilType: "loam",
    description:
      "Sun-grown leafy greens and seasonal row crops. Drip irrigation, crop rotation, and a small composting shed keep the soil happy year-round.",
    establishedAt: "2021-03-14",
    status: "active",
    managerName: "Priya Deshmukh",
    fieldsCount: 8,
    cropsCount: 14,
    yieldKg: 3840,
    createdAt: "2024-11-02T09:21:00.000Z",
    updatedAt: "2025-01-18T11:05:00.000Z",
  },
  {
    id: "farm-002",
    name: "Glasshouse 7",
    farmType: "greenhouse",
    location: "Nashik, Maharashtra",
    sizeAcres: 4.2,
    soilType: "sandy_loam",
    description:
      "Climate-controlled polytunnels for tomatoes, cucumbers, and sweet peppers. Hydroponic troughs and a heated propagation bench.",
    establishedAt: "2022-08-01",
    status: "active",
    managerName: "Rohan Kulkarni",
    fieldsCount: 5,
    cropsCount: 9,
    yieldKg: 6210,
    createdAt: "2024-11-04T14:00:00.000Z",
    updatedAt: "2025-02-09T08:32:00.000Z",
  },
  {
    id: "farm-003",
    name: "Misty Hills",
    farmType: "outdoor",
    location: "Lonavala, Maharashtra",
    sizeAcres: 22.8,
    soilType: "clay_loam",
    description:
      "Terraced hillside farm growing strawberries, beans, and millets. Contour bunding and mulching keep erosion in check through the monsoons.",
    establishedAt: "2019-06-22",
    status: "active",
    managerName: "Anita Pawar",
    fieldsCount: 12,
    cropsCount: 18,
    yieldKg: 5120,
    createdAt: "2024-11-09T10:45:00.000Z",
    updatedAt: "2025-02-22T16:10:00.000Z",
  },
  {
    id: "farm-004",
    name: "Riverbend Mixed",
    farmType: "mixed",
    location: "Kolhapur, Maharashtra",
    sizeAcres: 7.6,
    soilType: "silt",
    description:
      "Indoor seedling nursery pairs with outdoor finishing beds. Specializes in herbs and high-value salad mixes for urban buyers.",
    establishedAt: "2023-01-10",
    status: "active",
    managerName: "Vikram Shetty",
    fieldsCount: 6,
    cropsCount: 22,
    yieldKg: 2890,
    createdAt: "2024-12-01T12:00:00.000Z",
    updatedAt: "2025-03-04T09:15:00.000Z",
  },
  {
    id: "farm-005",
    name: "Hollow Co. Vertical",
    farmType: "vertical",
    location: "Mumbai, Maharashtra",
    sizeAcres: 0.6,
    soilType: "peaty",
    description:
      "Five-tier vertical racks growing microgreens and edible flowers in a converted warehouse. Subscribes to nearby restaurants weekly.",
    establishedAt: "2024-02-18",
    status: "active",
    managerName: "Saanvi Iyer",
    fieldsCount: 3,
    cropsCount: 11,
    yieldKg: 740,
    createdAt: "2024-12-15T08:30:00.000Z",
    updatedAt: "2025-03-11T14:55:00.000Z",
  },
  {
    id: "farm-006",
    name: "Cocoon Indoor",
    farmType: "indoor",
    location: "Bengaluru, Karnataka",
    sizeAcres: 1.4,
    soilType: "clay",
    description:
      "Sealed grow rooms with full-spectrum LEDs. Produces butterhead and romaine lettuce on a 28-day cycle year-round.",
    establishedAt: "2023-09-05",
    status: "active",
    managerName: "Karthik Rao",
    fieldsCount: 4,
    cropsCount: 7,
    yieldKg: 1980,
    createdAt: "2025-01-06T11:20:00.000Z",
    updatedAt: "2025-03-18T07:40:00.000Z",
  },
  {
    id: "farm-007",
    name: "Westwind Orchard",
    farmType: "outdoor",
    location: "Satara, Maharashtra",
    sizeAcres: 18.0,
    soilType: "clay_loam",
    description:
      "Mango, guava, and custard apple orchard with intercropping of legumes. Drip-irrigated and wind-break planted.",
    establishedAt: "2018-04-12",
    status: "active",
    managerName: "Meera Joshi",
    fieldsCount: 9,
    cropsCount: 6,
    yieldKg: 9740,
    createdAt: "2025-01-12T09:00:00.000Z",
    updatedAt: "2025-03-21T13:25:00.000Z",
  },
  {
    id: "farm-008",
    name: "Sprout Lab",
    farmType: "indoor",
    location: "Pune, Maharashtra",
    sizeAcres: 0.9,
    soilType: "loam",
    description:
      "Experimental microgreens facility — broccoli, radish, pea shoots. Direct-to-chef deliveries six days a week.",
    establishedAt: "2024-07-21",
    status: "planning",
    managerName: "Aditya Nair",
    fieldsCount: 2,
    cropsCount: 9,
    yieldKg: 320,
    createdAt: "2025-02-02T10:00:00.000Z",
    updatedAt: "2025-03-25T12:00:00.000Z",
  },
  {
    id: "farm-009",
    name: "Valley Greens",
    farmType: "greenhouse",
    location: "Mahabaleshwar, Maharashtra",
    sizeAcres: 3.5,
    soilType: "sandy",
    description:
      "High-altitude greenhouse specializing in strawberries and exotic salad leaves. Cool nights give the fruit a richer flavor.",
    establishedAt: "2022-11-30",
    status: "active",
    managerName: "Naina Patil",
    fieldsCount: 4,
    cropsCount: 8,
    yieldKg: 4320,
    createdAt: "2025-02-08T13:45:00.000Z",
    updatedAt: "2025-03-29T08:10:00.000Z",
  },
  {
    id: "farm-010",
    name: "North Block Pilot",
    farmType: "vertical",
    location: "Nagpur, Maharashtra",
    sizeAcres: 0.4,
    soilType: "peaty",
    description:
      "Pilot vertical rack testing basil and mint under purple-spectrum LEDs. Yield data feeds the larger Riverbend Mixed trial.",
    establishedAt: "2025-01-04",
    status: "planning",
    managerName: "Vikram Shetty",
    fieldsCount: 1,
    cropsCount: 4,
    yieldKg: 90,
    createdAt: "2025-03-01T15:00:00.000Z",
    updatedAt: "2025-03-30T09:00:00.000Z",
  },
  {
    id: "farm-011",
    name: "Old Mill Farm",
    farmType: "outdoor",
    location: "Solapur, Maharashtra",
    sizeAcres: 30.0,
    soilType: "sandy",
    description:
      "Heritage farm growing drought-tolerant millets and pulses. Cover-cropped between seasons and lightly grazed in winter.",
    establishedAt: "2015-10-02",
    status: "archived",
    managerName: "Bhaskar Mane",
    fieldsCount: 14,
    cropsCount: 7,
    yieldKg: 6420,
    createdAt: "2024-10-20T08:00:00.000Z",
    updatedAt: "2025-01-04T17:30:00.000Z",
  },
  {
    id: "farm-012",
    name: "Coastal Greenhouse",
    farmType: "greenhouse",
    location: "Ratnagiri, Maharashtra",
    sizeAcres: 5.5,
    soilType: "sandy_loam",
    description:
      "Salt-air-tolerant greenhouse growing capsicum and cherry tomatoes. Seaweed sprays and mulched beds keep moisture even.",
    establishedAt: "2021-12-19",
    status: "active",
    managerName: "Priya Deshmukh",
    fieldsCount: 5,
    cropsCount: 6,
    yieldKg: 4860,
    createdAt: "2024-11-22T11:30:00.000Z",
    updatedAt: "2025-02-14T10:05:00.000Z",
  },
];
