-- Seed lookup data for farm types (growing environments)
INSERT INTO farm_types (name, display_name, description) VALUES
    ('indoor',     'Indoor',     'Fully controlled environment inside a building — a grow room, warehouse, or vertical rack system where light, temperature, humidity, CO2, and nutrients are all managed artificially. Crops are usually grown soilless (hydroponics or aeroponics) under LED lighting, enabling year-round production regardless of outside weather. Best suited to leafy greens, herbs, and microgreens. Water use is minimal and pests are largely excluded, but energy for lighting and cooling is the main operating cost.'),
    ('outdoor',    'Outdoor',    'Traditional open-field farming where crops grow in natural soil under sunlight and rainfall, following seasonal sowing-to-harvest cycles. Suited to large-scale production of grains, vegetables, fruits, and fodder at the lowest cost per unit area. Success depends heavily on weather, soil health, irrigation, and pest pressure, so planning revolves around seasons, rotations, and machinery schedules rather than environmental controls.'),
    ('greenhouse', 'Greenhouse', 'Protected cultivation inside a glass or poly-covered structure that traps solar warmth while shielding crops from rain, wind, and many pests. Climate is actively managed — ventilation, heating, shading, and humidity control — which extends the growing season and raises yields well above open-field levels on the same footprint. Commonly used for tomatoes, cucumbers, peppers, and flowers, typically with drip irrigation and growing bags or beds. Strikes a balance between the control of indoor farming and the costs of open-field growing.'),
    ('mixed',      'Mixed',      'A farm that runs two or more growing environments side by side — for example open fields plus a greenhouse or an indoor grow room. The combination spreads weather and market risk, keeps supply steady across seasons, and lets high-value sensitive crops stay protected while bulk crops grow outside. Planning involves sequencing production across environments so they complement rather than duplicate each other.')
ON CONFLICT (name) DO NOTHING;

-- Seed lookup data for zone types (production area within a farm)
INSERT INTO zone_types (name, display_name, cultivation_mode, description) VALUES
    ('soil',      'Soil plot',     'soil',  'A ground-level cultivated plot where crops root directly into native or amended soil. The standard model for field vegetables, tubers, cereals, and orchards, with management centres on tillage, organic matter, crop rotation, cover cropping, and irrigation matched to soil tests. Lowest setup cost but the most exposed to weather, weeds, and soil-borne pests. Daily logs track soil moisture, planting, weeding, fertilisation, and harvest stage keyed to a chosen soil type.'),
    ('hydro',     'Hydroponic system', 'hydro', 'A soilless cultivation zone where plant roots sit in or are bathed by a nutrient-rich water solution, with substrate limited to rockwool, coco, perlite, or net pots. Delivers fast growth, high density, and tight control over EC, pH, and feed cycles, ideal for leafy greens, herbs, and some fruiting crops indoors. Daily logs centre on reservoir EC/pH, water temperature, flow, and the specific hydro system type (NFT, DWC, Ebb & Flow, etc.).'),
    ('aquaponic', 'Aquaponic',     'other', 'A closed-loop ecosystem that links a fish tank with hydroponic grow beds: fish waste supplies ammonia, beneficial bacteria convert it to nitrates, and the plants filter the water before it returns to the fish. Produces both protein (tilapia, catfish) and vegetables (lettuce, herbs, greens) in one recirculating loop. Demands careful balancing of fish feed rate, biofilter health, pH (~6.5–7.0), and ammonia/nitrite/nitrate levels tracked daily alongside plant growth.'),
    ('mushroom',  'Mushroom room', 'other', 'A dark, climate-sealed room used to grow fungi on sterilised substrates such as straw, sawdust, or hardwood blocks. Temperature, humidity (often 80–95% RH), fresh-air exchange (CO2 control), and lighting are tightly tuned to each phase — colonisation versus fruiting. Common crops are oyster, shiitake, lion’s mane, and button mushrooms. Daily logs track substrate batch, spawn run, pinning, flush number, contamination, and yield per block.')
ON CONFLICT (name) DO NOTHING;

-- Seed lookup data for soil types (texture / drainage profile)
INSERT INTO soil_types (name, display_name, water_retention, drainage, description) VALUES
    ('loamy',      'Loamy',       'high',   'good',      'A balanced mix of sand, silt, and clay (~40-40-20) that is widely considered the ideal agricultural soil. It holds moisture and nutrients well yet drains freely enough to avoid waterlogging, is easy to work across a wide moisture range, and resists crusting. Supports almost all vegetables, fruits, and cereals with minimal amendment, making it the default benchmark against which other soils are compared for yield potential and management effort.'),
    ('sandy',      'Sandy',       'low',    'excellent', 'Coarse-textured soil dominated by large mineral particles that drain very quickly and warm early in spring. Easy to cultivate and forgiving of over-watering, but it leaks nutrients fast, holds little moisture, and dries out between rains, so it needs frequent light irrigation and steady organic matter or fertigation. Best for root crops (carrots, potatoes), asparagus, and early-season vegetables, and is least suited to moisture-loving greens in peak summer.'),
    ('clay',       'Clay',        'high',   'poor',       'Fine-textured, nutrient-rich soil whose tiny particles pack tightly, giving high water and cation-holding capacity but slow, poor drainage and a heavy, sticky workability when wet, hard and cracked when dry. Productive once well-managed — holds fertiliser well and suits rice, cabbage, and deep-rooted perennials — but demands drainage, raised beds, gypsum, and timing tillage to the narrow “friable” moisture window to avoid compaction.'),
    ('silt',       'Silt',        'medium', 'medium',     'Smooth, flour-fine soil of intermediate particle size that feels silky when dry and slippery when wet. It retains more water and nutrients than sand yet drains better than clay, and is moderately fertile and easy to work. Its main weakness is surface crusting and erosion on slopes, which can block seedlings and wash off topsoil, so counter with organic matter, cover crops, and minimal tillage. Good for most vegetables, moisture-loving herbs, and lush greens.'),
    ('sandy_loam', 'Sandy loam',  'medium', 'good',      'A light, friable soil leaning toward sand but with enough silt, clay, and organic matter to hold moisture and nutrients better than pure sand. Drains well, warms fast, and is one of the easiest tilths to seed and transplant into, making it popular for market gardens. Needs regular irrigation and mulching in dry spells and benefits from compost to sustain nutrient supply, making it excellent for root vegetables, alliums, and direct-seeded salad crops.'),
    ('clay_loam',  'Clay loam',   'high',   'medium',     'A heavier but still workable soil that blends clay’s nutrient and water-holding power with enough sand and silt to improve drainage and tilth. Holds moisture through dry periods and retains fertiliser well, supporting high yields of fruiting and Brassica crops. Slightly slower to warm and dry in spring than sandy soils, so avoid working it when wet, and use raised beds and cover crops to keep structure open and prevent surface capping on heavy sites.')
ON CONFLICT (name) DO NOTHING;

-- Seed lookup data for hydroponic system types
INSERT INTO hydro_system_types (name, display_name, description) VALUES
    ('nft',         'NFT',          'Nutrient Film Technique: a thin, continuously flowing film of nutrient solution (1–3 mm deep) passes over bare plant roots in sloped channels, draining back to a reservoir. Roots stay oxygenated by the air-water interface while constantly fed, making NFT light on water and great for leafy greens and herbs. Very sensitive to pump or flow interruption — roots dry within minutes — so it needs reliable power, level sensors, and is rarely used for heavy fruiting crops.'),
    ('dwc',         'DWC',          'Deep Water Culture: plants float on polystyrene rafts over a large, aerated reservoir of nutrient solution with roots fully submerged. Simple, low-cost, forgiving of brief outages, and excellent for fast-growing leafy greens and herbs at scale. The big water mass buffers temperature and pH but is heavy, slow to change, and can spread root disease quickly, so success depends on continuous dissolved-oxygen (DO) levels above ~5 mg/L via air stones or cascades.'),
    ('ebb_flow',    'Ebb & Flow',   'Ebb and Flow (flood-and-drain): the growing tray is periodically flooded with nutrient solution from a reservoir and then drained back, pulling fresh air down to the roots between cycles. Versatile and suitable for a wide range of crops including fruiting plants grown in media beds (clay pebbles, rockwool). Cycle timing (often 3–4 floods per daylight hour) balances feed and aeration, and the wet-dry cycle is robust to short outages and encourages strong root systems.'),
    ('aeroponics',  'Aeroponics',   'Aeroponics: roots hang in air and are misted with fine droplets of nutrient solution on a timed cycle, giving the highest oxygen exposure of any system. Supports the fastest growth and highest yields per area, ideal for cuttings, microgreens, and high-value leafy crops. Requires high-pressure pumps, fine nozzles that clog easily, sterile water, and flawless timing — roots desiccate in minutes if misting fails, and the system is the most capital- and skill-intensive to run.'),
    ('drip',        'Drip',         'Drip irrigation hydroponics: emitters deliver a slow, measured stream of nutrient solution to each plant in an inert substrate such as rockwool, coco, or perlite, with runoff returned to the reservoir (recirculating) or drained to waste (run-to-waste). Highly flexible for fruiting crops like tomatoes, peppers, and cucumbers, scales well, and is robust to outages. Needs regular emitter and filter cleaning to prevent salt build-up and blockages that can starve individual plants.'),
    ('kratky',      'Kratky',        'Kratky method: a passive, non-circulating DWC set-up — roots sit in a reservoir with no pump or airstone, and as the solution level drops, the upper roots grow into the humid air gap and self-aerate while the lower roots keep drinking. Extremely simple, low-cost, and power-free, perfect for home growers and leafy greens on a single crop cycle. Not suited to long-term or heavy-feeding fruiting crops, and yield is limited by the starting volume of nutrient solution.')
ON CONFLICT (name) DO NOTHING;
